repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-ast

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.7.0
  hooks:
    -   id: python-use-type-annotations

- repo: https://github.com/PyCQA/isort
  rev: 5.7.0
  hooks:
    - id: isort
      name: isort

- repo: https://github.com/asottile/pyupgrade
  rev: v2.7.4
  hooks:
    - id: pyupgrade
      args: [--py37-plus]

- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
    - id: black

- repo: https://github.com/PyCQA/pylint
  rev: pylint-2.6.0
  hooks:
    - id: pylint
      args: [--rcfile=.pylintrc]
      files: ^jax_sindy/

- repo: https://gitlab.com/PyCQA/flake8
  rev: 3.8.4
  hooks:
    - id: flake8
      files: jax_sindy/

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.790
  hooks:
    - id: mypy
      files: jax_sindy/
